kind = "mobile"
previewPath = "/taxi-mobile/"
title = "Taxi Bensiamar Mobile"
version = "1.0.0"
id = "artifacts/taxi-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/taxi-mobile/" ]
localPort = 21206

[services.development]
run = "pnpm --filter @workspace/taxi-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/taxi-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/taxi-mobile", "run", "serve" ]

[services.env]
PORT = "21206"
BASE_PATH = "/taxi-mobile/"
